name 'rbenv'
maintainer 'Motonori IWAMURO'
maintainer_email 'vmi@nifty.com'
license 'mit'
description 'Installs/Configures system-wide rbenv for CentOS6'
long_description 'Installs/Configures system-wide rbenv CentOS6'
version '0.1.0'
